import './globals.css'
import type { Metadata } from 'next'
import { i18n } from '@/i8n-config'

export const metadata: Metadata = {
  title: 'i18n language switcher',
  description: 'Generated by create next app',
}
export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }))
}
export default function Root({
  children,
  params,
}: {
  children: React.ReactNode
  params: { lang: string }
}) {
  return (
    <html lang={params.lang}>
      <body>{children}</body>
    </html>
  )
}
